version: '3'

services:

  meilisearch:
    image: getmeili/meilisearch
    extra_hosts:
      - docker-desktop
    restart: unless-stopped
    networks:
      - local
    deploy:
      replicas: 1
      labels:
        feature.description: "Meilisearch"
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
    ports:
      - 7700:7700
    volumes:
      - meilisearch

volumes:
  meilisearch:
    driver: local

networks:
  local: