version: "3"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: arxiv
    ports:
      - 5432:5432
    volumes:
      - arxiv_pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test  
    ports:
      - 5050:80
    volumes:
      - arxiv_pgadmin:/var/lib/pgadmin
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    ports:
      - 9200:9200
    volumes:
      - arxiv_elasticsearch:/usr/share/elasticsearch/data
    mem_limit: 4g

  kibana:      
    image: docker.elastic.co/kibana/kibana:8.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  frontend_server: # example deployment
    build: ./frontend_server
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/static

volumes:
  arxiv_pg:
  arxiv_pgadmin:
  arxiv_elasticsearch:
